### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by anduz** [Shoggomo/traefik_dynamic_public_whitelist#1]
Hi, I followed you instructions, added the specified code to traefik.yml
and this to a dynamic files my-router: section

        middlewares: "public_ipwhitelist@plugin-traefik_dynamic_public_whitelist" 
But I get an error in log:
ERR error="middleware \"public_ipwhitelist@plugin-traefik_dynamic_public_whitelist\" does not exist" entryPointName=websecure routerName=jellyfin@file
Can you please tell me what I'm missing?

**Comment by anduz** [comment]
It's working now, maybe this helps someone:
Commented out the line containig: **nil**
```
providers:
  plugin:
    traefik_dynamic_public_whitelist:
      pollInterval: "120s"                                 # optional, default is "300s"
      ipv4Resolver: "https://api4.ipify.org/?format=text"  # optional, default is "https://api4.ipify.org?format=text" (needs to provide only the public ip on request)
      ipv6Resolver: "https://api6.ipify.org/?format=text"  # optional, default is "https://api6.ipify.org?format=text" (needs to provide only the public ip on request)
      whitelistIPv6: false                                 # optional, default is false
      additionalSourceRange: 192.168.0.1/24                # optional, additional source ranges, that should be accepted
      ipStrategy:                                          # optional, see https://doc.traefik.io/traefik/middlewares/http/ipwhitelist/#configuration-options for more info
        depth: 0                                           # optional
        # excludedIPs: nil                                   # optional
```
Had to specify version like this:
```
experimental:
  plugins:
    traefik_dynamic_public_whitelist:
      moduleName: github.com/Shoggomo/traefik_dynamic_public_whitelist
      version: v0.1.5
```

Maybe you can modify the code to avoid this warning:

>  WRN Middleware "public_ipwhitelist@plugin-traefik_dynamic_public_whitelist" of type IPWhiteList is deprecated, please use IPAllowList instead.
